############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3

# [[main]]
# name = "Elements"
# url = "/elements"
# weight = 3

[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Authors"
url = "/authors"
weight = 1

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "/categories"
# weight = 2

[[main]]
parent = "Pages"
name = "Tags"
url = "/tags"
weight = 2

[[main]]
parent = "Pages"
name = "Contact"
url = "/contact"
weight = 3

[[main]]
parent = "Pages"
name = "Email List"
url = "/email-list"
weight = 4

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Blog"
url = "/blog"
weight = 2

# [[footer]]
# name = "Elements"
# url = "/elements"
# weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "/privacy-policy"
# weight = 3
