[build]
publish = "public"
command = "yarn project-setup; yarn build"

[build.environment]
HUGO_VERSION = "0.147.3"
GO_VERSION = "1.24.2"

[context.production.environment]
HUGO_VERSION = "0.147.3"
GO_VERSION = "1.24.2"
